import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import statistics
import pyreadr #Load R dataset
import inspect
import os
from scipy.stats import t # t - student 
        
#for usernanme y set directorio

user = os.getlogin()   # Username

# Set directorio

os.chdir(f"C:/Users/{user}/Documents/GitHub/1ECO35_2022_2") # Set directorio

cps2012_env = pyreadr.read_r("data/cps2012.Rdata") # output formato diccionario


cps2012_env  # es un diccionario. En la llave "data" está la base de datos 
cps2012 = cps2012_env[ 'data' ] # extrae información almacenada en la llave data del diccionario cps2012_env
dt = cps2012.describe()

#Para crear lista hay que hacer algo con listas
lista = ['lnw','female','widowed', 'divorced', 'separated', 'nevermarried', 'hsd08', 'hsd911', 'hsg', 'cg', 'ad', 'mw', 'so', 'we', 'exp1', 'exp2', 'exp3', 'exp4', 'weight', 'ne', 'sc']
#Creamos la clase
class OLSRegClass(object): 
    __slots__ = [ '__X',  'Y', 'lista', 'RobustStandardError']
    def __init__(self, X:pd.DataFrame, Y:pd.Series, lista, RobustStandardError=False): 
        
        self.__X = X
        self.Y = Y
        self.RobustStandarError=RobustStandardError
        self.lista = lista

#Método 1

    def Coeficientes(self):
        
        self.columns = self.X.columns.tolist() # nombre de la base de datos como objeto lista
        
        self.n = self.X.shape[0] # numero de observaciones, # self.n "Se crea un nuevo atributo"
        k = self.X.shape[1] + 1 #numero de variables y el intercepto
        self.X1 = np.column_stack((np.ones(self.n ), self.X.to_numpy() ))  # self.X.to_numpy()  # DataFrame to numpy
        self.Y1 = self.Y.to_numpy().reshape(self.n  ,1)  #reshape(-1  ,1)
        
        self.beta = np.linalg.inv(self.X1.T @ self.X1) @ ((self.X1.T) @ self.Y1 )
        self.nk = self.n - k 

#Método 2 y 3    
    def Error_var_cov_intcof(self):              
            
            if self.RobustStandardError:
                
                self.y_est =  self.X1 @ self.beta
                self.error = self.Y1 - self.y_est 
                sigma =  sum(list( map( lambda x: x**2 , self.error)   )) / self.nk 
                self.Var = sigma*np.linalg.inv(self.X.T @ self.X) #Matríz de varianzas y covarianzas caso no robusto
                self.sd = np.sqrt( np.diag(self.Var) ) #Desviación estandar o errores estandar
                self.límite_inferior = self.beta-1.96*self.sd 
                self.límite_superior = self.beta+1.96*self.sd
                
            else:
                
                self.y_est =  self.X1 @ self.beta
                self.error = self.Y1 - self.y_est
                matrix_robust = np.diag(list( map( lambda x: x**2 , self.error)))  
                self.Var = np.linalg.inv(self.X.T @ self.X) @ self.X.T @ matrix_robust @ self.X @ np.linalg.inv(self.X.T @ self.X)
                self.sd = np.sqrt( np.diag(self.Var) )
                self.límite_inferior = self.beta-1.96*self.sd
                self.límite_superior = self.beta+1.96*self.sd

#Método 4
    
    def R2yMSE(self):
            
            self.Coeficientes()  # run function 
             
            self.SCR = sum(list( map( lambda x: x**2 , self.error)))
            self.SCT = sum(list( map( lambda x: x**2 , self.Y - np.mean(self.y_est))))
            self.rmse = (self.SCR/self.n)**0.5
            R2 = 1 - self.SCR/self.SCT
            
#Método 5

    def _Table(self, *Kargs):
        
        lista = ['lnw','female','widowed', 'divorced', 'separated', 'nevermarried', 'hsd08', 'hsd911', 'hsg', 'cg', 'ad', 'mw', 'so', 'we', 'exp1', 'exp2', 'exp3', 'exp4', 'weight', 'ne', 'sc']
        # run functions
    
        self.R2()
        self.Coeficientes()
        scr = self.SCR
        sigma =  scr / self.nk
        Var = sigma*np.linalg.inv(self.X1.T @ self.X1)
        sd = np.sqrt( np.diag(Var) )
        t_est = np.absolute(self.beta/sd)
        pvalue = (1 - t.cdf(t_est, df=self.nk) ) * 2
        lower_bound = self.beta-1.96*sd
        upper_bound = self.beta+1.96*sd
        rmse = (scr/self.n)**0.5
    
        if (Kargs['Output'] == "DataFrame"):

               df = pd.DataFrame( {"OLS": self.beta.flatten() , "standar_error" : sd.flatten(),"Pvalue" : pvalue.flatten() , "Lower_bound":lower_bound.flatten() ,
               "Upper_bound":upper_bound.flatten() , "Root_MSE":rmse.flatten() , "R2": self.R2.flatten()})
    
           #self.beta.flatten() # multy-array a simple array 
            
        elif (Kargs['Output'] == "Diccionario"):

               df ={"OLS": self.beta.flatten() , "standar_error" : sd.flatten(),"Pvalue" : pvalue.flatten() , "Lower_bound":lower_bound.flatten() ,
               "Upper_bound":upper_bound.flatten() , "Root_MSE":rmse.flatten() , "R2": self.R2.flatten()}


        return df

cps2012_env  # es un diccionario. En la llave "data" está la base de datos 
cps2012 = cps2012_env[ 'data' ] # extrae información almacenada en la llave data del diccionario cps2012_env

variance_cols = cps2012.var().to_numpy() # to numpy    
Dataset = cps2012.iloc[ : ,  np.where( variance_cols != 0   )[0] ]    
X = Dataset.iloc[:,1:10]
Y = Dataset[['lnw']]   
OLSRegClass(X, Y,lista,RobustStandardError=True)

#Pregunta 2####
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "90e53f84",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<style>\n",
       "    div#notebook-container    { width: 75%; }\n",
       "    div#menubar-container     { width: 95%; }\n",
       "    div#maintoolbar-container { width: 65%; }a\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from IPython.display import display, HTML\n",
    "\n",
    "display(HTML(data=\"\"\"\n",
    "<style>\n",
    "    div#notebook-container    { width: 75%; }\n",
    "    div#menubar-container     { width: 95%; }\n",
    "    div#maintoolbar-container { width: 65%; }a\n",
    "</style>\n",
    "\"\"\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "d596a6bf",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from pandas import DataFrame,Series"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d5d95a3c",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pyreadstat in c:\\users\\sabina\\anaconda3\\lib\\site-packages (1.1.9)\n",
      "Requirement already satisfied: pandas>=1.2.0 in c:\\users\\sabina\\anaconda3\\lib\\site-packages (from pyreadstat) (1.4.2)\n",
      "Requirement already satisfied: numpy>=1.18.5 in c:\\users\\sabina\\anaconda3\\lib\\site-packages (from pandas>=1.2.0->pyreadstat) (1.21.5)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\sabina\\anaconda3\\lib\\site-packages (from pandas>=1.2.0->pyreadstat) (2021.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in c:\\users\\sabina\\anaconda3\\lib\\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\sabina\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->pyreadstat) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install pyreadstat "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "1778f7a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: savReaderWriter in c:\\users\\sabina\\anaconda3\\lib\\site-packages (3.4.2)\n"
     ]
    }
   ],
   "source": [
    "# para guardar y abrir en formato spss\n",
    "!pip install savReaderWriter \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "6b95cf54",
   "metadata": {},
   "outputs": [],
   "source": [
    "# cargamos sav usando pandas\n",
    "data_administrativa = pd.read_spss( r\"../../data/data_administrativa.sav\" )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "14432a93",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>MES</th>\n",
       "      <th>CONGLOME</th>\n",
       "      <th>VIVIENDA</th>\n",
       "      <th>HOGAR</th>\n",
       "      <th>CODPERSO</th>\n",
       "      <th>UBIGEO</th>\n",
       "      <th>DOMINIO</th>\n",
       "      <th>ESTRATO</th>\n",
       "      <th>P201P</th>\n",
       "      <th>P203</th>\n",
       "      <th>P203A</th>\n",
       "      <th>P203B</th>\n",
       "      <th>P204</th>\n",
       "      <th>P205</th>\n",
       "      <th>P206</th>\n",
       "      <th>P207</th>\n",
       "      <th>P208A</th>\n",
       "      <th>P208B</th>\n",
       "      <th>P209</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>010108</td>\n",
       "      <td>136</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>100111</td>\n",
       "      <td>Sierra Centro</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200101081361102</td>\n",
       "      <td>Esposo(a)/compañero(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>43.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>020257</td>\n",
       "      <td>093</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>250107</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200202570931104</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>17.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>015537</td>\n",
       "      <td>065</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>040126</td>\n",
       "      <td>Sierra Sur</td>\n",
       "      <td>De 500 000 a más habitantes</td>\n",
       "      <td>20200155370651104</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>9.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2019</td>\n",
       "      <td>10</td>\n",
       "      <td>010614</td>\n",
       "      <td>043</td>\n",
       "      <td>11</td>\n",
       "      <td>07</td>\n",
       "      <td>130901</td>\n",
       "      <td>Sierra Norte</td>\n",
       "      <td>De 20 000 a 49 999 habitantes</td>\n",
       "      <td>20190106140431107</td>\n",
       "      <td>Otros parientes</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>No</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>4.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>009390</td>\n",
       "      <td>096</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>230110</td>\n",
       "      <td>Costa Sur</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20180093900961104</td>\n",
       "      <td>Panel</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85030</th>\n",
       "      <td>2020</td>\n",
       "      <td>12</td>\n",
       "      <td>007337</td>\n",
       "      <td>004</td>\n",
       "      <td>11</td>\n",
       "      <td>01</td>\n",
       "      <td>140105</td>\n",
       "      <td>Costa Norte</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200073370041101</td>\n",
       "      <td>Jefe/Jefa</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>65.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85031</th>\n",
       "      <td>2019</td>\n",
       "      <td>04</td>\n",
       "      <td>008226</td>\n",
       "      <td>084</td>\n",
       "      <td>13</td>\n",
       "      <td>02</td>\n",
       "      <td>160112</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190082260841302</td>\n",
       "      <td>Otros no parientes</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>89.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Viudo(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85032</th>\n",
       "      <td>2019</td>\n",
       "      <td>05</td>\n",
       "      <td>008965</td>\n",
       "      <td>060</td>\n",
       "      <td>11</td>\n",
       "      <td>03</td>\n",
       "      <td>210101</td>\n",
       "      <td>Sierra Sur</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190089650601103</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>20.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85033</th>\n",
       "      <td>2020</td>\n",
       "      <td>05</td>\n",
       "      <td>010311</td>\n",
       "      <td>022</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>200501</td>\n",
       "      <td>Costa Norte</td>\n",
       "      <td>De 50 000 a 99 999 habitantes</td>\n",
       "      <td>20200103110221102</td>\n",
       "      <td>Esposo(a)/compañero(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>48.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85034</th>\n",
       "      <td>2020</td>\n",
       "      <td>11</td>\n",
       "      <td>018778</td>\n",
       "      <td>155</td>\n",
       "      <td>11</td>\n",
       "      <td>06</td>\n",
       "      <td>160404</td>\n",
       "      <td>Selva</td>\n",
       "      <td>Área de Empadronamiento Rural (AER) Compuesto</td>\n",
       "      <td>20200187781551106</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>22.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Conviviente</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>85035 rows × 20 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       year MES CONGLOME VIVIENDA HOGAR CODPERSO  UBIGEO        DOMINIO  \\\n",
       "0      2020  06   010108      136    11       02  100111  Sierra Centro   \n",
       "1      2020  06   020257      093    11       04  250107          Selva   \n",
       "2      2020  06   015537      065    11       04  040126     Sierra Sur   \n",
       "3      2019  10   010614      043    11       07  130901   Sierra Norte   \n",
       "4      2020  06   009390      096    11       04  230110      Costa Sur   \n",
       "...     ...  ..      ...      ...   ...      ...     ...            ...   \n",
       "85030  2020  12   007337      004    11       01  140105    Costa Norte   \n",
       "85031  2019  04   008226      084    13       02  160112          Selva   \n",
       "85032  2019  05   008965      060    11       03  210101     Sierra Sur   \n",
       "85033  2020  05   010311      022    11       02  200501    Costa Norte   \n",
       "85034  2020  11   018778      155    11       06  160404          Selva   \n",
       "\n",
       "                                              ESTRATO              P201P  \\\n",
       "0                     De 100 000 a 499 999 habitantes  20200101081361102   \n",
       "1                     De 100 000 a 499 999 habitantes  20200202570931104   \n",
       "2                         De 500 000 a más habitantes  20200155370651104   \n",
       "3                       De 20 000 a 49 999 habitantes  20190106140431107   \n",
       "4                     De 100 000 a 499 999 habitantes  20180093900961104   \n",
       "...                                               ...                ...   \n",
       "85030                 De 100 000 a 499 999 habitantes  20200073370041101   \n",
       "85031                 De 100 000 a 499 999 habitantes  20190082260841302   \n",
       "85032                 De 100 000 a 499 999 habitantes  20190089650601103   \n",
       "85033                   De 50 000 a 99 999 habitantes  20200103110221102   \n",
       "85034   Área de Empadronamiento Rural (AER) Compuesto  20200187781551106   \n",
       "\n",
       "                         P203  P203A               P203B P204 P205 P206  \\\n",
       "0      Esposo(a)/compañero(a)    NaN                 NaN   Si   No  NaN   \n",
       "1         Hijo(a)/Hijastro(a)    NaN                 NaN   Si   No  NaN   \n",
       "2         Hijo(a)/Hijastro(a)    NaN                 NaN   Si   No  NaN   \n",
       "3             Otros parientes    2.0             Hijo(a)   No  NaN   No   \n",
       "4                       Panel    NaN                 NaN  NaN  NaN  NaN   \n",
       "...                       ...    ...                 ...  ...  ...  ...   \n",
       "85030               Jefe/Jefa    1.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "85031      Otros no parientes    0.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "85032     Hijo(a)/Hijastro(a)    1.0             Hijo(a)   Si   No  NaN   \n",
       "85033  Esposo(a)/compañero(a)    NaN                 NaN   Si   No  NaN   \n",
       "85034     Hijo(a)/Hijastro(a)    2.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "\n",
       "         P207  P208A  P208B         P209  \n",
       "0       Mujer   43.0    NaN    Casado(a)  \n",
       "1      Hombre   17.0    NaN   Soltero(a)  \n",
       "2       Mujer    9.0    NaN          NaN  \n",
       "3       Mujer    4.0    NaN          NaN  \n",
       "4         NaN    NaN    NaN          NaN  \n",
       "...       ...    ...    ...          ...  \n",
       "85030  Hombre   65.0    NaN    Casado(a)  \n",
       "85031   Mujer   89.0    NaN     Viudo(a)  \n",
       "85032  Hombre   20.0    NaN   Soltero(a)  \n",
       "85033   Mujer   48.0    NaN    Casado(a)  \n",
       "85034  Hombre   22.0    NaN  Conviviente  \n",
       "\n",
       "[85035 rows x 20 columns]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data_administrativa"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "376cb6a9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>MES</th>\n",
       "      <th>CONGLOME</th>\n",
       "      <th>VIVIENDA</th>\n",
       "      <th>HOGAR</th>\n",
       "      <th>CODPERSO</th>\n",
       "      <th>UBIGEO</th>\n",
       "      <th>DOMINIO</th>\n",
       "      <th>ESTRATO</th>\n",
       "      <th>P201P</th>\n",
       "      <th>P203</th>\n",
       "      <th>P203A</th>\n",
       "      <th>P203B</th>\n",
       "      <th>P204</th>\n",
       "      <th>P205</th>\n",
       "      <th>P206</th>\n",
       "      <th>P207</th>\n",
       "      <th>P208A</th>\n",
       "      <th>P208B</th>\n",
       "      <th>P209</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85030</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85031</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85032</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85033</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85034</th>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>85035 rows × 20 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        year    MES  CONGLOME  VIVIENDA  HOGAR  CODPERSO  UBIGEO  DOMINIO  \\\n",
       "0      False  False     False     False  False     False   False    False   \n",
       "1      False  False     False     False  False     False   False    False   \n",
       "2      False  False     False     False  False     False   False    False   \n",
       "3      False  False     False     False  False     False   False    False   \n",
       "4      False  False     False     False  False     False   False    False   \n",
       "...      ...    ...       ...       ...    ...       ...     ...      ...   \n",
       "85030  False  False     False     False  False     False   False    False   \n",
       "85031  False  False     False     False  False     False   False    False   \n",
       "85032  False  False     False     False  False     False   False    False   \n",
       "85033  False  False     False     False  False     False   False    False   \n",
       "85034  False  False     False     False  False     False   False    False   \n",
       "\n",
       "       ESTRATO  P201P   P203  P203A  P203B   P204   P205   P206   P207  P208A  \\\n",
       "0        False  False  False   True   True  False  False   True  False  False   \n",
       "1        False  False  False   True   True  False  False   True  False  False   \n",
       "2        False  False  False   True   True  False  False   True  False  False   \n",
       "3        False  False  False  False  False  False   True  False  False  False   \n",
       "4        False  False  False   True   True   True   True   True   True   True   \n",
       "...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   \n",
       "85030    False  False  False  False  False  False  False   True  False  False   \n",
       "85031    False  False  False  False  False  False  False   True  False  False   \n",
       "85032    False  False  False  False  False  False  False   True  False  False   \n",
       "85033    False  False  False   True   True  False  False   True  False  False   \n",
       "85034    False  False  False  False  False  False  False   True  False  False   \n",
       "\n",
       "       P208B   P209  \n",
       "0       True  False  \n",
       "1       True  False  \n",
       "2       True   True  \n",
       "3       True   True  \n",
       "4       True   True  \n",
       "...      ...    ...  \n",
       "85030   True  False  \n",
       "85031   True  False  \n",
       "85032   True  False  \n",
       "85033   True  False  \n",
       "85034   True  False  \n",
       "\n",
       "[85035 rows x 20 columns]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Mostramos las variables que presentan missing values\n",
    "\n",
    "data_administrativa. isnull()\n",
    "\n",
    "# Se puede observar que hay missing values en las siguientes vairables:\n",
    "# P203A, P203B, P204, P205, P206, P207, P208A, P208B, P209"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "3d54b206",
   "metadata": {},
   "outputs": [],
   "source": [
    "import savReaderWriter as sav  # importamos sav (paquete)\n",
    "\n",
    "\n",
    "with sav.SavHeaderReader( r\"../../data/data_administrativa.sav\" , ioUtf8=True) as header:\n",
    "    metadata = header.all() # guardamos dataset\n",
    "    labels_data_administrativa = metadata.valueLabels  # para obtener etiquetas de los valores de variables \n",
    "    var_labels_data_administrativa = metadata.varLabels # etiquetas de varibales \n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "69240e49",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dict"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "type(labels_data_administrativa)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "b6510251",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dict_keys(['DOMINIO', 'ESTRATO', 'P203', 'P203B', 'P204', 'P205', 'P206', 'P207', 'P209'])"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "labels_data_administrativa.keys()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "742e3ab0",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>MES</th>\n",
       "      <th>CONGLOME</th>\n",
       "      <th>VIVIENDA</th>\n",
       "      <th>HOGAR</th>\n",
       "      <th>CODPERSO</th>\n",
       "      <th>UBIGEO</th>\n",
       "      <th>DOMINIO</th>\n",
       "      <th>ESTRATO</th>\n",
       "      <th>P201P</th>\n",
       "      <th>P203</th>\n",
       "      <th>P203A</th>\n",
       "      <th>P203B</th>\n",
       "      <th>P204</th>\n",
       "      <th>P205</th>\n",
       "      <th>P206</th>\n",
       "      <th>P207</th>\n",
       "      <th>P208A</th>\n",
       "      <th>P208B</th>\n",
       "      <th>P209</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>010108</td>\n",
       "      <td>136</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>100111</td>\n",
       "      <td>Sierra Centro</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200101081361102</td>\n",
       "      <td>Esposo(a)/compañero(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>43.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>020257</td>\n",
       "      <td>093</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>250107</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200202570931104</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>17.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>015537</td>\n",
       "      <td>065</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>040126</td>\n",
       "      <td>Sierra Sur</td>\n",
       "      <td>De 500 000 a más habitantes</td>\n",
       "      <td>20200155370651104</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>9.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2019</td>\n",
       "      <td>10</td>\n",
       "      <td>010614</td>\n",
       "      <td>043</td>\n",
       "      <td>11</td>\n",
       "      <td>07</td>\n",
       "      <td>130901</td>\n",
       "      <td>Sierra Norte</td>\n",
       "      <td>De 20 000 a 49 999 habitantes</td>\n",
       "      <td>20190106140431107</td>\n",
       "      <td>Otros parientes</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>No</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>4.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>009390</td>\n",
       "      <td>096</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>230110</td>\n",
       "      <td>Costa Sur</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20180093900961104</td>\n",
       "      <td>Panel</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85030</th>\n",
       "      <td>2020</td>\n",
       "      <td>12</td>\n",
       "      <td>007337</td>\n",
       "      <td>004</td>\n",
       "      <td>11</td>\n",
       "      <td>01</td>\n",
       "      <td>140105</td>\n",
       "      <td>Costa Norte</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200073370041101</td>\n",
       "      <td>Jefe/Jefa</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>65.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85031</th>\n",
       "      <td>2019</td>\n",
       "      <td>04</td>\n",
       "      <td>008226</td>\n",
       "      <td>084</td>\n",
       "      <td>13</td>\n",
       "      <td>02</td>\n",
       "      <td>160112</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190082260841302</td>\n",
       "      <td>Otros no parientes</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>89.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Viudo(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85032</th>\n",
       "      <td>2019</td>\n",
       "      <td>05</td>\n",
       "      <td>008965</td>\n",
       "      <td>060</td>\n",
       "      <td>11</td>\n",
       "      <td>03</td>\n",
       "      <td>210101</td>\n",
       "      <td>Sierra Sur</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190089650601103</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>20.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85033</th>\n",
       "      <td>2020</td>\n",
       "      <td>05</td>\n",
       "      <td>010311</td>\n",
       "      <td>022</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>200501</td>\n",
       "      <td>Costa Norte</td>\n",
       "      <td>De 50 000 a 99 999 habitantes</td>\n",
       "      <td>20200103110221102</td>\n",
       "      <td>Esposo(a)/compañero(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>48.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85034</th>\n",
       "      <td>2020</td>\n",
       "      <td>11</td>\n",
       "      <td>018778</td>\n",
       "      <td>155</td>\n",
       "      <td>11</td>\n",
       "      <td>06</td>\n",
       "      <td>160404</td>\n",
       "      <td>Selva</td>\n",
       "      <td>Área de Empadronamiento Rural (AER) Compuesto</td>\n",
       "      <td>20200187781551106</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>22.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Conviviente</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>85035 rows × 20 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       year MES CONGLOME VIVIENDA HOGAR CODPERSO  UBIGEO        DOMINIO  \\\n",
       "0      2020  06   010108      136    11       02  100111  Sierra Centro   \n",
       "1      2020  06   020257      093    11       04  250107          Selva   \n",
       "2      2020  06   015537      065    11       04  040126     Sierra Sur   \n",
       "3      2019  10   010614      043    11       07  130901   Sierra Norte   \n",
       "4      2020  06   009390      096    11       04  230110      Costa Sur   \n",
       "...     ...  ..      ...      ...   ...      ...     ...            ...   \n",
       "85030  2020  12   007337      004    11       01  140105    Costa Norte   \n",
       "85031  2019  04   008226      084    13       02  160112          Selva   \n",
       "85032  2019  05   008965      060    11       03  210101     Sierra Sur   \n",
       "85033  2020  05   010311      022    11       02  200501    Costa Norte   \n",
       "85034  2020  11   018778      155    11       06  160404          Selva   \n",
       "\n",
       "                                              ESTRATO              P201P  \\\n",
       "0                     De 100 000 a 499 999 habitantes  20200101081361102   \n",
       "1                     De 100 000 a 499 999 habitantes  20200202570931104   \n",
       "2                         De 500 000 a más habitantes  20200155370651104   \n",
       "3                       De 20 000 a 49 999 habitantes  20190106140431107   \n",
       "4                     De 100 000 a 499 999 habitantes  20180093900961104   \n",
       "...                                               ...                ...   \n",
       "85030                 De 100 000 a 499 999 habitantes  20200073370041101   \n",
       "85031                 De 100 000 a 499 999 habitantes  20190082260841302   \n",
       "85032                 De 100 000 a 499 999 habitantes  20190089650601103   \n",
       "85033                   De 50 000 a 99 999 habitantes  20200103110221102   \n",
       "85034   Área de Empadronamiento Rural (AER) Compuesto  20200187781551106   \n",
       "\n",
       "                         P203  P203A               P203B P204 P205 P206  \\\n",
       "0      Esposo(a)/compañero(a)    NaN                 NaN   Si   No  NaN   \n",
       "1         Hijo(a)/Hijastro(a)    NaN                 NaN   Si   No  NaN   \n",
       "2         Hijo(a)/Hijastro(a)    NaN                 NaN   Si   No  NaN   \n",
       "3             Otros parientes    2.0             Hijo(a)   No  NaN   No   \n",
       "4                       Panel    NaN                 NaN  NaN  NaN  NaN   \n",
       "...                       ...    ...                 ...  ...  ...  ...   \n",
       "85030               Jefe/Jefa    1.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "85031      Otros no parientes    0.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "85032     Hijo(a)/Hijastro(a)    1.0             Hijo(a)   Si   No  NaN   \n",
       "85033  Esposo(a)/compañero(a)    NaN                 NaN   Si   No  NaN   \n",
       "85034     Hijo(a)/Hijastro(a)    2.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "\n",
       "         P207  P208A  P208B         P209  \n",
       "0       Mujer   43.0    NaN    Casado(a)  \n",
       "1      Hombre   17.0    NaN   Soltero(a)  \n",
       "2       Mujer    9.0    NaN          NaN  \n",
       "3       Mujer    4.0    NaN          NaN  \n",
       "4         NaN    NaN    NaN          NaN  \n",
       "...       ...    ...    ...          ...  \n",
       "85030  Hombre   65.0    NaN    Casado(a)  \n",
       "85031   Mujer   89.0    NaN     Viudo(a)  \n",
       "85032  Hombre   20.0    NaN   Soltero(a)  \n",
       "85033   Mujer   48.0    NaN    Casado(a)  \n",
       "85034  Hombre   22.0    NaN  Conviviente  \n",
       "\n",
       "[85035 rows x 20 columns]"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data_administrativa"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "734c2f7b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'DOMINIO': {1.0: 'Costa Norte',\n",
       "  2.0: 'Costa Centro',\n",
       "  3.0: 'Costa Sur',\n",
       "  4.0: 'Sierra Norte',\n",
       "  5.0: 'Sierra Centro',\n",
       "  6.0: 'Sierra Sur',\n",
       "  7.0: 'Selva',\n",
       "  8.0: 'Lima Metropolitana'},\n",
       " 'ESTRATO': {1.0: ' De 500 000 a más habitantes',\n",
       "  2.0: ' De 100 000 a 499 999 habitantes',\n",
       "  3.0: ' De 50 000 a 99 999 habitantes',\n",
       "  4.0: ' De 20 000 a 49 999 habitantes',\n",
       "  5.0: 'De 2 000 a 19 999 habitantes',\n",
       "  6.0: ' De 500 a 1 999 habitantes',\n",
       "  7.0: ' Área de Empadronamiento Rural (AER) Compuesto',\n",
       "  8.0: ' Área de Empadronamiento Rural (AER) Simple'},\n",
       " 'P203': {0.0: 'Panel',\n",
       "  1.0: 'Jefe/Jefa',\n",
       "  2.0: 'Esposo(a)/compañero(a)',\n",
       "  3.0: 'Hijo(a)/Hijastro(a)',\n",
       "  4.0: 'Yerno/Nuera',\n",
       "  5.0: 'Nieto(a)',\n",
       "  6.0: 'Padres/Suegros',\n",
       "  7.0: 'Otros parientes',\n",
       "  8.0: 'Trabajador Hogar',\n",
       "  9.0: 'Pensionista',\n",
       "  10.0: 'Otros no parientes',\n",
       "  11.0: 'Hermano(a)'},\n",
       " 'P203B': {1.0: 'Jefe/jefa de hogar',\n",
       "  2.0: 'Esposa(o)',\n",
       "  3.0: 'Hijo(a)',\n",
       "  6.0: 'Padres/suegros'},\n",
       " 'P204': {1.0: 'Si', 2.0: 'No'},\n",
       " 'P205': {1.0: 'Si', 2.0: 'No'},\n",
       " 'P206': {1.0: 'Si', 2.0: 'No'},\n",
       " 'P207': {1.0: 'Hombre', 2.0: 'Mujer'},\n",
       " 'P209': {1.0: 'Conviviente',\n",
       "  2.0: 'Casado(a)',\n",
       "  3.0: 'Viudo(a)',\n",
       "  4.0: 'Divorciado(a)',\n",
       "  5.0: 'Separado(a)',\n",
       "  6.0: 'Soltero(a)'}}"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "labels_data_administrativa"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "10327135",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'year': '',\n",
       " 'MES': '',\n",
       " 'CONGLOME': '',\n",
       " 'VIVIENDA': '',\n",
       " 'HOGAR': '',\n",
       " 'CODPERSO': '',\n",
       " 'UBIGEO': '',\n",
       " 'DOMINIO': 'Dominio geográfico',\n",
       " 'ESTRATO': 'Estrato geográfico',\n",
       " 'P201P': '',\n",
       " 'P203': '¿Cuál es la relación de parentesco con el jefe(a) del hogar',\n",
       " 'P203A': '',\n",
       " 'P203B': 'Relación de parentesco con el jefe(a) del núcleo familiar',\n",
       " 'P204': '¿Es miembro del hogar?',\n",
       " 'P205': '¿Se encuentra ausente del hogar 30 días o más?',\n",
       " 'P206': '¿Está presente en el hogar 30 días o más?',\n",
       " 'P207': 'Sexo',\n",
       " 'P208A': '',\n",
       " 'P208B': '',\n",
       " 'P209': '¿Cuál es su estado civil o conyugal?'}"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "var_labels_data_administrativa"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "4867bdeb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# adding labels to variables enapres2020_1 from pandas \n",
    "\n",
    "data_administrativa.attrs[ 'value_labels' ] = labels_data_administrativa # value's labels \n",
    "data_administrativa.attrs[ 'var_labels' ] = var_labels_data_administrativa # var labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "f205f280",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>MES</th>\n",
       "      <th>CONGLOME</th>\n",
       "      <th>VIVIENDA</th>\n",
       "      <th>HOGAR</th>\n",
       "      <th>CODPERSO</th>\n",
       "      <th>UBIGEO</th>\n",
       "      <th>DOMINIO</th>\n",
       "      <th>ESTRATO</th>\n",
       "      <th>P201P</th>\n",
       "      <th>P203</th>\n",
       "      <th>P203A</th>\n",
       "      <th>P203B</th>\n",
       "      <th>P204</th>\n",
       "      <th>P205</th>\n",
       "      <th>P206</th>\n",
       "      <th>P207</th>\n",
       "      <th>P208A</th>\n",
       "      <th>P208B</th>\n",
       "      <th>P209</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>010108</td>\n",
       "      <td>136</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>100111</td>\n",
       "      <td>Sierra Centro</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200101081361102</td>\n",
       "      <td>Esposo(a)/compañero(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>43.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>020257</td>\n",
       "      <td>093</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>250107</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200202570931104</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>17.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>015537</td>\n",
       "      <td>065</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>040126</td>\n",
       "      <td>Sierra Sur</td>\n",
       "      <td>De 500 000 a más habitantes</td>\n",
       "      <td>20200155370651104</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>9.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2019</td>\n",
       "      <td>10</td>\n",
       "      <td>010614</td>\n",
       "      <td>043</td>\n",
       "      <td>11</td>\n",
       "      <td>07</td>\n",
       "      <td>130901</td>\n",
       "      <td>Sierra Norte</td>\n",
       "      <td>De 20 000 a 49 999 habitantes</td>\n",
       "      <td>20190106140431107</td>\n",
       "      <td>Otros parientes</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>No</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>4.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2020</td>\n",
       "      <td>06</td>\n",
       "      <td>009390</td>\n",
       "      <td>096</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>230110</td>\n",
       "      <td>Costa Sur</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20180093900961104</td>\n",
       "      <td>Panel</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85030</th>\n",
       "      <td>2020</td>\n",
       "      <td>12</td>\n",
       "      <td>007337</td>\n",
       "      <td>004</td>\n",
       "      <td>11</td>\n",
       "      <td>01</td>\n",
       "      <td>140105</td>\n",
       "      <td>Costa Norte</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200073370041101</td>\n",
       "      <td>Jefe/Jefa</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>65.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85031</th>\n",
       "      <td>2019</td>\n",
       "      <td>04</td>\n",
       "      <td>008226</td>\n",
       "      <td>084</td>\n",
       "      <td>13</td>\n",
       "      <td>02</td>\n",
       "      <td>160112</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190082260841302</td>\n",
       "      <td>Otros no parientes</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>89.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Viudo(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85032</th>\n",
       "      <td>2019</td>\n",
       "      <td>05</td>\n",
       "      <td>008965</td>\n",
       "      <td>060</td>\n",
       "      <td>11</td>\n",
       "      <td>03</td>\n",
       "      <td>210101</td>\n",
       "      <td>Sierra Sur</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190089650601103</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>20.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85033</th>\n",
       "      <td>2020</td>\n",
       "      <td>05</td>\n",
       "      <td>010311</td>\n",
       "      <td>022</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>200501</td>\n",
       "      <td>Costa Norte</td>\n",
       "      <td>De 50 000 a 99 999 habitantes</td>\n",
       "      <td>20200103110221102</td>\n",
       "      <td>Esposo(a)/compañero(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>48.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85034</th>\n",
       "      <td>2020</td>\n",
       "      <td>11</td>\n",
       "      <td>018778</td>\n",
       "      <td>155</td>\n",
       "      <td>11</td>\n",
       "      <td>06</td>\n",
       "      <td>160404</td>\n",
       "      <td>Selva</td>\n",
       "      <td>Área de Empadronamiento Rural (AER) Compuesto</td>\n",
       "      <td>20200187781551106</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>22.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Conviviente</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>85035 rows × 20 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       year MES CONGLOME VIVIENDA HOGAR CODPERSO  UBIGEO        DOMINIO  \\\n",
       "0      2020  06   010108      136    11       02  100111  Sierra Centro   \n",
       "1      2020  06   020257      093    11       04  250107          Selva   \n",
       "2      2020  06   015537      065    11       04  040126     Sierra Sur   \n",
       "3      2019  10   010614      043    11       07  130901   Sierra Norte   \n",
       "4      2020  06   009390      096    11       04  230110      Costa Sur   \n",
       "...     ...  ..      ...      ...   ...      ...     ...            ...   \n",
       "85030  2020  12   007337      004    11       01  140105    Costa Norte   \n",
       "85031  2019  04   008226      084    13       02  160112          Selva   \n",
       "85032  2019  05   008965      060    11       03  210101     Sierra Sur   \n",
       "85033  2020  05   010311      022    11       02  200501    Costa Norte   \n",
       "85034  2020  11   018778      155    11       06  160404          Selva   \n",
       "\n",
       "                                              ESTRATO              P201P  \\\n",
       "0                     De 100 000 a 499 999 habitantes  20200101081361102   \n",
       "1                     De 100 000 a 499 999 habitantes  20200202570931104   \n",
       "2                         De 500 000 a más habitantes  20200155370651104   \n",
       "3                       De 20 000 a 49 999 habitantes  20190106140431107   \n",
       "4                     De 100 000 a 499 999 habitantes  20180093900961104   \n",
       "...                                               ...                ...   \n",
       "85030                 De 100 000 a 499 999 habitantes  20200073370041101   \n",
       "85031                 De 100 000 a 499 999 habitantes  20190082260841302   \n",
       "85032                 De 100 000 a 499 999 habitantes  20190089650601103   \n",
       "85033                   De 50 000 a 99 999 habitantes  20200103110221102   \n",
       "85034   Área de Empadronamiento Rural (AER) Compuesto  20200187781551106   \n",
       "\n",
       "                         P203  P203A               P203B P204 P205 P206  \\\n",
       "0      Esposo(a)/compañero(a)    NaN                 NaN   Si   No  NaN   \n",
       "1         Hijo(a)/Hijastro(a)    NaN                 NaN   Si   No  NaN   \n",
       "2         Hijo(a)/Hijastro(a)    NaN                 NaN   Si   No  NaN   \n",
       "3             Otros parientes    2.0             Hijo(a)   No  NaN   No   \n",
       "4                       Panel    NaN                 NaN  NaN  NaN  NaN   \n",
       "...                       ...    ...                 ...  ...  ...  ...   \n",
       "85030               Jefe/Jefa    1.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "85031      Otros no parientes    0.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "85032     Hijo(a)/Hijastro(a)    1.0             Hijo(a)   Si   No  NaN   \n",
       "85033  Esposo(a)/compañero(a)    NaN                 NaN   Si   No  NaN   \n",
       "85034     Hijo(a)/Hijastro(a)    2.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "\n",
       "         P207  P208A  P208B         P209  \n",
       "0       Mujer   43.0    NaN    Casado(a)  \n",
       "1      Hombre   17.0    NaN   Soltero(a)  \n",
       "2       Mujer    9.0    NaN          NaN  \n",
       "3       Mujer    4.0    NaN          NaN  \n",
       "4         NaN    NaN    NaN          NaN  \n",
       "...       ...    ...    ...          ...  \n",
       "85030  Hombre   65.0    NaN    Casado(a)  \n",
       "85031   Mujer   89.0    NaN     Viudo(a)  \n",
       "85032  Hombre   20.0    NaN   Soltero(a)  \n",
       "85033   Mujer   48.0    NaN    Casado(a)  \n",
       "85034  Hombre   22.0    NaN  Conviviente  \n",
       "\n",
       "[85035 rows x 20 columns]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data_administrativa"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "5a21ed2d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>MES</th>\n",
       "      <th>CONGLOME</th>\n",
       "      <th>VIVIENDA</th>\n",
       "      <th>HOGAR</th>\n",
       "      <th>CODPERSO</th>\n",
       "      <th>UBIGEO</th>\n",
       "      <th>DOMINIO</th>\n",
       "      <th>ESTRATO</th>\n",
       "      <th>P201P</th>\n",
       "      <th>P203</th>\n",
       "      <th>P203A</th>\n",
       "      <th>P203B</th>\n",
       "      <th>P204</th>\n",
       "      <th>P205</th>\n",
       "      <th>P206</th>\n",
       "      <th>P207</th>\n",
       "      <th>P208A</th>\n",
       "      <th>P208B</th>\n",
       "      <th>P209</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2019</td>\n",
       "      <td>10</td>\n",
       "      <td>010614</td>\n",
       "      <td>043</td>\n",
       "      <td>11</td>\n",
       "      <td>07</td>\n",
       "      <td>130901</td>\n",
       "      <td>Sierra Norte</td>\n",
       "      <td>De 20 000 a 49 999 habitantes</td>\n",
       "      <td>20190106140431107</td>\n",
       "      <td>Otros parientes</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>No</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>4.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2019</td>\n",
       "      <td>03</td>\n",
       "      <td>008010</td>\n",
       "      <td>059</td>\n",
       "      <td>11</td>\n",
       "      <td>03</td>\n",
       "      <td>150801</td>\n",
       "      <td>Costa Centro</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190080100591103</td>\n",
       "      <td>Otros parientes</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>32.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>2019</td>\n",
       "      <td>07</td>\n",
       "      <td>009625</td>\n",
       "      <td>071</td>\n",
       "      <td>11</td>\n",
       "      <td>01</td>\n",
       "      <td>250105</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190096250711101</td>\n",
       "      <td>Jefe/Jefa</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>64.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Conviviente</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>2020</td>\n",
       "      <td>07</td>\n",
       "      <td>010368</td>\n",
       "      <td>081</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>230104</td>\n",
       "      <td>Costa Sur</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20180103680811105</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>14.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>52</th>\n",
       "      <td>2019</td>\n",
       "      <td>12</td>\n",
       "      <td>005867</td>\n",
       "      <td>034</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>060101</td>\n",
       "      <td>Sierra Norte</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20170058670341102</td>\n",
       "      <td>Esposo(a)/compañero(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Esposa(o)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>53.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>84940</th>\n",
       "      <td>2019</td>\n",
       "      <td>12</td>\n",
       "      <td>008253</td>\n",
       "      <td>047</td>\n",
       "      <td>11</td>\n",
       "      <td>01</td>\n",
       "      <td>160113</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20170082530471101</td>\n",
       "      <td>Jefe/Jefa</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>80.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Conviviente</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>84945</th>\n",
       "      <td>2019</td>\n",
       "      <td>06</td>\n",
       "      <td>007982</td>\n",
       "      <td>008</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>150202</td>\n",
       "      <td>Costa Centro</td>\n",
       "      <td>De 20 000 a 49 999 habitantes</td>\n",
       "      <td>20170079820081102</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>19.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>84975</th>\n",
       "      <td>2020</td>\n",
       "      <td>09</td>\n",
       "      <td>007221</td>\n",
       "      <td>043</td>\n",
       "      <td>11</td>\n",
       "      <td>03</td>\n",
       "      <td>130901</td>\n",
       "      <td>Sierra Norte</td>\n",
       "      <td>De 20 000 a 49 999 habitantes</td>\n",
       "      <td>20170072210431103</td>\n",
       "      <td>Yerno/Nuera</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>38.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Conviviente</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>84982</th>\n",
       "      <td>2019</td>\n",
       "      <td>07</td>\n",
       "      <td>008806</td>\n",
       "      <td>114</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>200701</td>\n",
       "      <td>Costa Norte</td>\n",
       "      <td>De 50 000 a 99 999 habitantes</td>\n",
       "      <td>20170088061141104</td>\n",
       "      <td>Nieto(a)</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>6.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85000</th>\n",
       "      <td>2020</td>\n",
       "      <td>02</td>\n",
       "      <td>009338</td>\n",
       "      <td>017</td>\n",
       "      <td>11</td>\n",
       "      <td>03</td>\n",
       "      <td>230108</td>\n",
       "      <td>Costa Sur</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190093380171103</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>25.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>8270 rows × 20 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       year MES CONGLOME VIVIENDA HOGAR CODPERSO  UBIGEO       DOMINIO  \\\n",
       "3      2019  10   010614      043    11       07  130901  Sierra Norte   \n",
       "5      2019  03   008010      059    11       03  150801  Costa Centro   \n",
       "24     2019  07   009625      071    11       01  250105         Selva   \n",
       "33     2020  07   010368      081    11       04  230104     Costa Sur   \n",
       "52     2019  12   005867      034    11       02  060101  Sierra Norte   \n",
       "...     ...  ..      ...      ...   ...      ...     ...           ...   \n",
       "84940  2019  12   008253      047    11       01  160113         Selva   \n",
       "84945  2019  06   007982      008    11       02  150202  Costa Centro   \n",
       "84975  2020  09   007221      043    11       03  130901  Sierra Norte   \n",
       "84982  2019  07   008806      114    11       04  200701   Costa Norte   \n",
       "85000  2020  02   009338      017    11       03  230108     Costa Sur   \n",
       "\n",
       "                                ESTRATO              P201P  \\\n",
       "3         De 20 000 a 49 999 habitantes  20190106140431107   \n",
       "5       De 100 000 a 499 999 habitantes  20190080100591103   \n",
       "24      De 100 000 a 499 999 habitantes  20190096250711101   \n",
       "33      De 100 000 a 499 999 habitantes  20180103680811105   \n",
       "52      De 100 000 a 499 999 habitantes  20170058670341102   \n",
       "...                                 ...                ...   \n",
       "84940   De 100 000 a 499 999 habitantes  20170082530471101   \n",
       "84945     De 20 000 a 49 999 habitantes  20170079820081102   \n",
       "84975     De 20 000 a 49 999 habitantes  20170072210431103   \n",
       "84982     De 50 000 a 99 999 habitantes  20170088061141104   \n",
       "85000   De 100 000 a 499 999 habitantes  20190093380171103   \n",
       "\n",
       "                         P203  P203A               P203B P204 P205 P206  \\\n",
       "3             Otros parientes    2.0             Hijo(a)   No  NaN   No   \n",
       "5             Otros parientes    1.0             Hijo(a)   Si   No  NaN   \n",
       "24                  Jefe/Jefa    1.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "33        Hijo(a)/Hijastro(a)    NaN                 NaN   Si   No  NaN   \n",
       "52     Esposo(a)/compañero(a)    1.0           Esposa(o)   Si   No  NaN   \n",
       "...                       ...    ...                 ...  ...  ...  ...   \n",
       "84940               Jefe/Jefa    1.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "84945     Hijo(a)/Hijastro(a)    1.0             Hijo(a)   Si   No  NaN   \n",
       "84975             Yerno/Nuera    NaN                 NaN   Si   No  NaN   \n",
       "84982                Nieto(a)    2.0             Hijo(a)   Si   No  NaN   \n",
       "85000     Hijo(a)/Hijastro(a)    1.0             Hijo(a)   Si   No  NaN   \n",
       "\n",
       "         P207  P208A  P208B         P209  \n",
       "3       Mujer    4.0    NaN          NaN  \n",
       "5      Hombre   32.0    NaN   Soltero(a)  \n",
       "24     Hombre   64.0    NaN  Conviviente  \n",
       "33     Hombre   14.0    NaN   Soltero(a)  \n",
       "52      Mujer   53.0    NaN    Casado(a)  \n",
       "...       ...    ...    ...          ...  \n",
       "84940  Hombre   80.0    NaN  Conviviente  \n",
       "84945  Hombre   19.0    NaN   Soltero(a)  \n",
       "84975  Hombre   38.0    NaN  Conviviente  \n",
       "84982  Hombre    6.0    NaN          NaN  \n",
       "85000  Hombre   25.0    NaN   Soltero(a)  \n",
       "\n",
       "[8270 rows x 20 columns]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Se le pide detectar personas que fueran entrevistadas en ambos años. \n",
    "# para ello, se pide detectar duplicados a partir del identificador por persona : \n",
    "# conglome, vivienda, hogar y codperso.\n",
    "\n",
    "data_administrativa[ data_administrativa.loc[:, ['CONGLOME' , 'VIVIENDA', 'HOGAR', 'CODPERSO']].duplicated(keep = False) ]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "9171167c",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>MES</th>\n",
       "      <th>CONGLOME</th>\n",
       "      <th>VIVIENDA</th>\n",
       "      <th>HOGAR</th>\n",
       "      <th>CODPERSO</th>\n",
       "      <th>UBIGEO</th>\n",
       "      <th>DOMINIO</th>\n",
       "      <th>ESTRATO</th>\n",
       "      <th>P201P</th>\n",
       "      <th>P203</th>\n",
       "      <th>P203A</th>\n",
       "      <th>P203B</th>\n",
       "      <th>P204</th>\n",
       "      <th>P205</th>\n",
       "      <th>P206</th>\n",
       "      <th>P207</th>\n",
       "      <th>P208A</th>\n",
       "      <th>P208B</th>\n",
       "      <th>P209</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>56662</th>\n",
       "      <td>2019</td>\n",
       "      <td>04</td>\n",
       "      <td>005031</td>\n",
       "      <td>101</td>\n",
       "      <td>11</td>\n",
       "      <td>01</td>\n",
       "      <td>010201</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 20 000 a 49 999 habitantes</td>\n",
       "      <td>20190050311011101</td>\n",
       "      <td>Jefe/Jefa</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>45.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>70184</th>\n",
       "      <td>2019</td>\n",
       "      <td>02</td>\n",
       "      <td>005024</td>\n",
       "      <td>003</td>\n",
       "      <td>11</td>\n",
       "      <td>07</td>\n",
       "      <td>010401</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 2 000 a 19 999 habitantes</td>\n",
       "      <td>20150050240031105</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>Si</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>18.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49277</th>\n",
       "      <td>2019</td>\n",
       "      <td>11</td>\n",
       "      <td>009172</td>\n",
       "      <td>119</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>220501</td>\n",
       "      <td>Selva</td>\n",
       "      <td>De 2 000 a 19 999 habitantes</td>\n",
       "      <td>20160091721191102</td>\n",
       "      <td>Esposo(a)/compañero(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Esposa(o)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>32.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Conviviente</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49275</th>\n",
       "      <td>2019</td>\n",
       "      <td>12</td>\n",
       "      <td>005011</td>\n",
       "      <td>031</td>\n",
       "      <td>11</td>\n",
       "      <td>01</td>\n",
       "      <td>010101</td>\n",
       "      <td>Sierra Norte</td>\n",
       "      <td>De 20 000 a 49 999 habitantes</td>\n",
       "      <td>20190050110311101</td>\n",
       "      <td>Jefe/Jefa</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>58.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>70179</th>\n",
       "      <td>2019</td>\n",
       "      <td>01</td>\n",
       "      <td>008006</td>\n",
       "      <td>091</td>\n",
       "      <td>11</td>\n",
       "      <td>03</td>\n",
       "      <td>150801</td>\n",
       "      <td>Costa Centro</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20190080060911103</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>19.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37969</th>\n",
       "      <td>2020</td>\n",
       "      <td>04</td>\n",
       "      <td>016182</td>\n",
       "      <td>079</td>\n",
       "      <td>11</td>\n",
       "      <td>01</td>\n",
       "      <td>070102</td>\n",
       "      <td>Lima Metropolitana</td>\n",
       "      <td>De 500 000 a más habitantes</td>\n",
       "      <td>20200161820791101</td>\n",
       "      <td>Jefe/Jefa</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>43.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Casado(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37970</th>\n",
       "      <td>2020</td>\n",
       "      <td>11</td>\n",
       "      <td>016370</td>\n",
       "      <td>028</td>\n",
       "      <td>11</td>\n",
       "      <td>02</td>\n",
       "      <td>080106</td>\n",
       "      <td>Sierra Sur</td>\n",
       "      <td>De 100 000 a 499 999 habitantes</td>\n",
       "      <td>20200163700281102</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>1.0</td>\n",
       "      <td>Hijo(a)</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>27.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37971</th>\n",
       "      <td>2020</td>\n",
       "      <td>09</td>\n",
       "      <td>015516</td>\n",
       "      <td>011</td>\n",
       "      <td>11</td>\n",
       "      <td>04</td>\n",
       "      <td>030401</td>\n",
       "      <td>Sierra Sur</td>\n",
       "      <td>Área de Empadronamiento Rural (AER) Compuesto</td>\n",
       "      <td>20200155160111104</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>15.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37958</th>\n",
       "      <td>2020</td>\n",
       "      <td>09</td>\n",
       "      <td>005523</td>\n",
       "      <td>138</td>\n",
       "      <td>11</td>\n",
       "      <td>07</td>\n",
       "      <td>040102</td>\n",
       "      <td>Sierra Sur</td>\n",
       "      <td>De 500 000 a más habitantes</td>\n",
       "      <td>20170055231381103</td>\n",
       "      <td>Hermano(a)</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Mujer</td>\n",
       "      <td>48.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Soltero(a)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>85034</th>\n",
       "      <td>2020</td>\n",
       "      <td>11</td>\n",
       "      <td>018778</td>\n",
       "      <td>155</td>\n",
       "      <td>11</td>\n",
       "      <td>06</td>\n",
       "      <td>160404</td>\n",
       "      <td>Selva</td>\n",
       "      <td>Área de Empadronamiento Rural (AER) Compuesto</td>\n",
       "      <td>20200187781551106</td>\n",
       "      <td>Hijo(a)/Hijastro(a)</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Jefe/jefa de hogar</td>\n",
       "      <td>Si</td>\n",
       "      <td>No</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hombre</td>\n",
       "      <td>22.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Conviviente</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>85035 rows × 20 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       year MES CONGLOME VIVIENDA HOGAR CODPERSO  UBIGEO             DOMINIO  \\\n",
       "56662  2019  04   005031      101    11       01  010201               Selva   \n",
       "70184  2019  02   005024      003    11       07  010401               Selva   \n",
       "49277  2019  11   009172      119    11       02  220501               Selva   \n",
       "49275  2019  12   005011      031    11       01  010101        Sierra Norte   \n",
       "70179  2019  01   008006      091    11       03  150801        Costa Centro   \n",
       "...     ...  ..      ...      ...   ...      ...     ...                 ...   \n",
       "37969  2020  04   016182      079    11       01  070102  Lima Metropolitana   \n",
       "37970  2020  11   016370      028    11       02  080106          Sierra Sur   \n",
       "37971  2020  09   015516      011    11       04  030401          Sierra Sur   \n",
       "37958  2020  09   005523      138    11       07  040102          Sierra Sur   \n",
       "85034  2020  11   018778      155    11       06  160404               Selva   \n",
       "\n",
       "                                              ESTRATO              P201P  \\\n",
       "56662                   De 20 000 a 49 999 habitantes  20190050311011101   \n",
       "70184                    De 2 000 a 19 999 habitantes  20150050240031105   \n",
       "49277                    De 2 000 a 19 999 habitantes  20160091721191102   \n",
       "49275                   De 20 000 a 49 999 habitantes  20190050110311101   \n",
       "70179                 De 100 000 a 499 999 habitantes  20190080060911103   \n",
       "...                                               ...                ...   \n",
       "37969                     De 500 000 a más habitantes  20200161820791101   \n",
       "37970                 De 100 000 a 499 999 habitantes  20200163700281102   \n",
       "37971   Área de Empadronamiento Rural (AER) Compuesto  20200155160111104   \n",
       "37958                     De 500 000 a más habitantes  20170055231381103   \n",
       "85034   Área de Empadronamiento Rural (AER) Compuesto  20200187781551106   \n",
       "\n",
       "                         P203  P203A               P203B P204 P205 P206  \\\n",
       "56662               Jefe/Jefa    1.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "70184     Hijo(a)/Hijastro(a)    1.0             Hijo(a)   Si   Si  NaN   \n",
       "49277  Esposo(a)/compañero(a)    1.0           Esposa(o)   Si   No  NaN   \n",
       "49275               Jefe/Jefa    1.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "70179     Hijo(a)/Hijastro(a)    1.0             Hijo(a)   Si   No  NaN   \n",
       "...                       ...    ...                 ...  ...  ...  ...   \n",
       "37969               Jefe/Jefa    NaN                 NaN   Si   No  NaN   \n",
       "37970     Hijo(a)/Hijastro(a)    1.0             Hijo(a)   Si   No  NaN   \n",
       "37971     Hijo(a)/Hijastro(a)    NaN                 NaN   Si   No  NaN   \n",
       "37958              Hermano(a)    NaN                 NaN   Si   No  NaN   \n",
       "85034     Hijo(a)/Hijastro(a)    2.0  Jefe/jefa de hogar   Si   No  NaN   \n",
       "\n",
       "         P207  P208A  P208B         P209  \n",
       "56662  Hombre   45.0    NaN    Casado(a)  \n",
       "70184   Mujer   18.0    NaN   Soltero(a)  \n",
       "49277   Mujer   32.0    NaN  Conviviente  \n",
       "49275  Hombre   58.0    NaN    Casado(a)  \n",
       "70179  Hombre   19.0    NaN   Soltero(a)  \n",
       "...       ...    ...    ...          ...  \n",
       "37969   Mujer   43.0    NaN    Casado(a)  \n",
       "37970   Mujer   27.0    NaN   Soltero(a)  \n",
       "37971  Hombre   15.0    NaN   Soltero(a)  \n",
       "37958   Mujer   48.0    NaN   Soltero(a)  \n",
       "85034  Hombre   22.0    NaN  Conviviente  \n",
       "\n",
       "[85035 rows x 20 columns]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Ordene la base de datos a partir de las variables que identifican cada miembro y la variable de año (year) \n",
    "# Así podrá observar a cada individuo en ambos años.\n",
    "\n",
    "by_year = data_administrativa.sort_values('year',ascending=True)\n",
    "by_year\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "33245bf4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Finalmente crear una base de datos para cada año \n",
    "\n",
    "# Base de datos del año 2019 \n",
    "df_2019 = data_administrativa.loc[ data_administrativa.year == '2019', : ]\n",
    "df_2019\n",
    "# guardamos\n",
    "import pyreadstat\n",
    "pyreadstat.write_sav(data_administrativa,  r\"../../data/data_administrativa/data_2019_grupo8.sav\")\n",
    "\n",
    "# Base de datos del año 2020\n",
    "df_2020 = data_administrativa.loc[ data_administrativa.year == '2020', : ]\n",
    "df_2020\n",
    "\n",
    "pyreadstat.write_sav(data_administrativa,  r\"../../data/data_administrativa/data_2020_grupo8.sav\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d76c0298",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
